In [9]:
import numpy as np
import copy

In [26]:
l=np.arange(-10,20)
k=np.where(l<0)
divd = copy.deepcopy(l)
l[k] = -100


In [13]:
l/divd

C:\Users\xiyu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  10.        ,   11.11111111,   12.5       ,   14.28571429,
         16.66666667,   20.        ,   25.        ,   33.33333333,
         50.        ,  100.        ,           nan,    1.        ,
          1.        ,    1.        ,    1.        ,    1.        ,
          1.        ,    1.        ,    1.        ,    1.        ,
          1.        ,    1.        ,    1.        ,    1.        ,
          1.        ,    1.        ,    1.        ,    1.        ,
          1.        ,    1.        ])

In [27]:
l

array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100,    0,
          1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19])

In [28]:
l=l*divd

In [29]:
l

array([1000,  900,  800,  700,  600,  500,  400,  300,  200,  100,    0,
          1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361])

In [30]:
l

array([1000,  900,  800,  700,  600,  500,  400,  300,  200,  100,    0,
          1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361])

In [31]:
divd

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])